paths:
  data_dir: data/ddis/
  embeddings_zip: data/ddis/graph-embeddings.zip
  crowd_data: data/ddis/crowd_data.tsv
  graph: data/ddis/14_graph.nt
  graph_zip: data/ddis/graph.zip
  images: data/ddis/images.json
  images_zip: data/ddis/images.json.zip

paths_processed:
  processed_data_dir: data/processed/
  ent2lbl: data/processed/ent2lbl.pkl
  lbl2ent: data/processed/lbl2ent.pkl
  predicate_dict: data/processed/predicate_dict.pkl
  crowd_predicates: data/processed/crowd_predicates.pickle
  all_movies_dict: data/processed/all_movies_dict.pickle
  all_people_dict: data/processed/all_people_dict.pickle
  aggr_ans_dict: data/processed/aggr_ans_dict.pickle
  fixed_triples: data/processed/fixed_triples.pickle
  added_triples: data/processed/added_triples.pickle
  indirectSubclassOf_triples: data/processed/indirectSubclassOf_triples.pickle
  indirectSubclassOf_entities: data/processed/indirectSubclassOf_entities.pickle
  special_movies: data/processed/special_movies.pkl
  updated_graph: data/processed/updated_graph.nt

paths_embeddings:
  embeddings_dir: data/ddis/embeddings/ddis-graph-embeddings/
  entity_emb: data/ddis/embeddings/ddis-graph-embeddings/entity_embeds.npy
  relation_emb: data/ddis/embeddings/ddis-graph-embeddings/relation_embeds.npy
  entity_file: data/ddis/embeddings/ddis-graph-embeddings/entity_ids.del
  relation_file: data/ddis/embeddings/ddis-graph-embeddings/relation_ids.del

urls:
  base_url: https://files.ifi.uzh.ch/ddis/teaching/2023/ATAI/dataset/
  ddis_movie_graph_nt: https://files.ifi.uzh.ch/ddis/teaching/2023/ATAI/dataset/ddis-movie-graph.nt.zip
  ddis_graph_embeddings: https://files.ifi.uzh.ch/ddis/teaching/2023/ATAI/dataset/ddis-graph-embeddings.zip
  crowd_data_tsv: https://files.ifi.uzh.ch/ddis/teaching/2023/ATAI/dataset/crowd_data/crowd_data.tsv
  images: https://files.ifi.uzh.ch/ddis/teaching/2023/ATAI/dataset/movienet/images.json.zip

namespaces:
  WD: 'http://www.wikidata.org/entity/'
  WDT: 'http://www.wikidata.org/prop/direct/'
  DDIS: 'http://ddis.ch/atai/'
  RDFS: 'http://www.w3.org/2000/01/rdf-schema#'
  SCHEMA: 'http://schema.org/'
