paths:
  data_dir: data/
  ddis_movie_graph_nt: data/ddis-movie-graph.nt
  ddis_movie_graph_tsv: data/ddis-movie-graph.tsv
  ddis_graph_embeddings_zip: data/ddis-graph-embeddings.zip
  ddis_graph_embeddings_dir: data/graph-embeddings/
  crowd_data_tsv: data/crowd_data.tsv
  crowd_data_olat: data/crowd_data_olat_P344FullstopCorrected.tsv
  plots_csv: data/plots.csv
  user_comments_csv: data/user-comments.csv
  ent2lbl_path: data/ent2lbl.pkl
  lbl2ent_path: data/lbl2ent.pkl

urls:
  ddis_movie_graph_nt: https://files.ifi.uzh.ch/ddis/teaching/2023/ATAI/dataset/ddis-movie-graph.nt.zip
  ddis_movie_graph_tsv: https://files.ifi.uzh.ch/ddis/teaching/2023/ATAI/dataset/ddis-movie-graph.tsv.zip
  ddis_graph_embeddings: https://files.ifi.uzh.ch/ddis/teaching/2023/ATAI/dataset/ddis-graph-embeddings.zip
  crowd_data_tsv: https://files.ifi.uzh.ch/ddis/teaching/2023/ATAI/dataset/crowd_data/crowd_data.tsv
  crowd_data_olat: https://files.ifi.uzh.ch/ddis/teaching/2023/ATAI/dataset/crowd_data/crowd_data_olat_P344FullstopCorrected.tsv
  plots_csv: https://files.ifi.uzh.ch/ddis/teaching/2023/ATAI/dataset/plots.csv
  user_comments_csv: https://files.ifi.uzh.ch/ddis/teaching/2023/ATAI/dataset/user-comments.csv

namespaces:
  WD: 'http://www.wikidata.org/entity/'
  WDT: 'http://www.wikidata.org/prop/direct/'
  DDIS: 'http://ddis.ch/atai/'
  RDFS: 'http://www.w3.org/2000/01/rdf-schema#'
  SCHEMA: 'http://schema.org/'
